
package com.hf.ws.jdk.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IJdkWebService", targetNamespace = "http://jdk.ws.hf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IJdkWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething", targetNamespace = "http://jdk.ws.hf.com/", className = "com.hf.ws.jdk.client.DoSomething")
    @ResponseWrapper(localName = "doSomethingResponse", targetNamespace = "http://jdk.ws.hf.com/", className = "com.hf.ws.jdk.client.DoSomethingResponse")
    @Action(input = "http://jdk.ws.hf.com/IJdkWebService/doSomethingRequest", output = "http://jdk.ws.hf.com/IJdkWebService/doSomethingResponse")
    public String doSomething(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething2", targetNamespace = "http://jdk.ws.hf.com/", className = "com.hf.ws.jdk.client.DoSomething2")
    @ResponseWrapper(localName = "doSomething2Response", targetNamespace = "http://jdk.ws.hf.com/", className = "com.hf.ws.jdk.client.DoSomething2Response")
    @Action(input = "http://jdk.ws.hf.com/IJdkWebService/doSomething2Request", output = "http://jdk.ws.hf.com/IJdkWebService/doSomething2Response")
    public String doSomething2(
        @WebParam(name = "value", targetNamespace = "http://hf.jdk.ws/")
        String value);

}
