
package com.hf.ws.jdk.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JdkWebServiceImplService", targetNamespace = "http://jdk.ws.hf.com/", wsdlLocation = "http://localhost:8080/myspring/jdkWebService?wsdl")
public class JdkWebServiceImplService
    extends Service
{

    private final static URL JDKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JDKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName JDKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://jdk.ws.hf.com/", "JdkWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/myspring/jdkWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JDKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        JDKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public JdkWebServiceImplService() {
        super(__getWsdlLocation(), JDKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public JdkWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JDKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public JdkWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, JDKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public JdkWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JDKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public JdkWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JdkWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IJdkWebService
     */
    @WebEndpoint(name = "JdkWebServiceImplPort")
    public IJdkWebService getJdkWebServiceImplPort() {
        return super.getPort(new QName("http://jdk.ws.hf.com/", "JdkWebServiceImplPort"), IJdkWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJdkWebService
     */
    @WebEndpoint(name = "JdkWebServiceImplPort")
    public IJdkWebService getJdkWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jdk.ws.hf.com/", "JdkWebServiceImplPort"), IJdkWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JDKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw JDKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return JDKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
