package com.hf.entity;


import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.hf.entity.base.DataEntity;

@Entity
@Table(name = "user")
public class User extends DataEntity{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// ==============
	// PRIVATE FIELDS
	// ==============
	// An autogenerated id (unique for each user in the db)

	// The user email
	@NotNull
	private String email;
	// The user name
	@NotNull
	private String name;
	
	//@Enumerated(EnumType.STRING)
    private String role;

    private String username;
    
    private String password;

	// ==============
	// PUBLIC METHODS
	// ==============
	public User() {
	}


	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

} // class User

